# Dankwoord {-}

\chaptermark{DANKWOORD}
\thispagestyle{empty}
\markboth{DANKWOORD}{DANKWOORD}


Allereerst wil ik mijn ouders bedanken. Bart en Anne, jullie onvoorwaardelijke liefde, mijn hele leven lang al, betekent alles voor mij. Er zijn zeker ook minder leuke tijden geweest, maar altijd stonden jullie voor mij klaar en zochten jullie naar wat het beste voor mij zou zijn. Ook als dat betekende dat jullie me letterlijk naar de andere kant van de wereld moesten laten gaan in de slechte tijden. Ik heb bovendien het geluk dat jullie niet alleen goede en fijne ouders voor mij zijn geweest, ik kan het tegenwoordig ook nog eens ontzettend goed met jullie vinden. Ik hoop dat we nog heel lang van elkaars gezelschap kunnen genieten!

Aan Jeanette Reefman en Oscar Westers. Zonder jullie beide had ik waarschijnlijk nooit de middelbare school afgemaakt, laat staan dat ik nu mijn PhD had kunnen behalen. Bedankt voor alle hulp op een moment dat ik het erg goed kon gebruiken. Jullie hebben een ontzettend grote en positieve impact op mijn leven gehad. 

Rens, bedankt voor alles. Ik had niet gedacht werken leuk te zullen vinden maar het is onder jouw begeleiding een geweldige tijd gebleken. Ik heb heel veel van je geleerd, niet alleen inhoudelijk maar ook hoe je politiek en zakelijk allerlei situaties beter kan aanpakken. Dit zal mij in de toekomst zeker heel veel helpen. Daarnaast waardeer ik heel erg je enthousiasme, maar vooral ook je zorgzame benadering. Je probeert te pushen als het kan, af te remmen als het nodig is en oog te houden voor de zo belangrijke werk-privé balans in het leven van degene die je begeleidt. We hebben straks nog een paar maanden om wat leuke projecten samen te doen, maar waar ik ook in de toekomst beland, hoop ik dat we elkaar weer tegenkomen. Het was een waar genoegen met je samen te werken en je als baas te hebben.

Nancy en Gerko, wat fijn dat jullie mijn copromotoren wilden zijn ondanks het late moment in het project. Gerko, als assistent in je summerschool leerde ik tijdens het lesgeven een hoop bij en bovendien is het gewoon ontzettend gezellig met je kletsen, over statistiek, of wat dan ook. Nancy, zonder jouw inzichten zouden we niet in staat zijn geweest om de elicitatie methoden te ontwikkelen zoals we dat gedaan hebben. Bedankt voor je immer enthousiaste input. Dan wil ik ook nog Diederick bedanken die mij in het begin veel heeft geleerd over communicatie: wie is je publiek? Kees, niet alleen bedankt voor alle gezelligheid en dat je een ontzettend fijne collega was, ik heb ook enorm veel geleerd over statistiek en programmeren van jou. Marthe, bedankt voor de ontzettend fijne samenwerkingen. Het was zowel gezellig als heel prettig met je samenwerken. Maartje, bedankt voor de fijne samenwerking en gezellige koppen koffie. Jean-Paul, bedankt dat je mij enthousiast hebt gemaakt voor statistiek tijdens mijn bachelor opdracht, master en studentassistentschap.  

\newpage

Bob, thank you so much for inviting me to visit you. Not only have I learned so much from you and everyone at Columbia, you have been more welcoming than I could ever have expected and you have made my stay a lot of fun. To Mitzi, Matthijs, Jenna, Charles, Lauren, Jonah and all others who have been so kind and friendly. Thank you for the wonderful time that I have had in New York. 


Alex, Roelof en Cato, ondanks alle hierboven genoemde namen zijn jullie zeker mijn eerste docenten geweest. Ik heb zoveel geleerd door altijd bij jullie aan te willen haken en mee te willen doen in jullie discussies. Ik zeg het misschien niet vaak genoeg, maar ik houd heel veel van jullie. Ard, Armelle en Ingrid, bedankt dat jullie zo'n fijne schoonfamilie zijn voor mij, maar vooral dat jullie mijn broers en zus zo gelukkig maken.

Voor mijn paranimfen. Bart, er wordt ons weleens verweten net een getrouwd stel te zijn. Misschien is dat na al die jaren samen wonen en zoveel tijd samen doorbrengen ook wel niet zo gek. Ik kan alles bij je kwijt en je staat altijd voor me klaar. We hebben veel plezier samen en voeren altijd discussies over alles, van politiek tot aan voetbal. Je bent mijn beste maat. Roelof, je bent al even genoemd bij de familie, maar je bent meer voor mij dan een broer. Je bent al sinds kleins af aan mijn vriend. Je gaf me wiskunde les toen ik op de basisschool zat, je bent mijn trainer geweest, je kwam ophalen van school op vrijdagen om te kaarten, eerst in pico daarna in Camelot. Alle vakanties die we samen hebben doorgebracht, alle jaren samen in Enschede en nu in Utrecht. Ik ben ontzettend trots op de fijne persoon die jij geworden bent en gelukkig dat je in mijn leven bent. 

Voor mijn vrienden, ik prijs mezelf erg gelukkig met de vele fijne mensen in mijn leven. Er is zoveel meer dat ik tegen jullie zou willen zeggen, maar misschien wel het belangrijkste: jullie verrijken mijn leven enorm. 

Om te beginnen met mijn oudste vrienden, Eric en Stijn Jonasse. In het begin van onze studententijden is het contact wat minder geweest, maar wat ben ik blij dat het daarna weer meer is geworden. Eric, door de enorme open gesprekken met jou leer ik nog altijd over mezelf en over de wereld om mij heen. Stijn, toen ik terug kwam op het stedelijk kwam ik bij jou in de klas. Sinds die dag kan ik bij jou altijd terecht voor een intellectuele uitdaging. Of we die nou combineren met een wandeling, museum bezoek, een (strategisch) spel spelen of een profielwerkstuk samen schrijven. Rianne, na elkaar jaren niet gezien te hebben kwamen we elkaar toevallig weer tegen op een feestje. Ik geniet ontzettend van het uren lange kletsen met je sindsdien, elke keer weer.

Simon, Mats, Thomas, Mick, Guus en Leon. Een onafhankelijke jaarclub met mensen bij wie ik nooit in dezelfde stad heb gewoond (Simon en Leon) en die allemaal een paar jaar ouder zijn dan ikzelf. Ik kijk nog altijd een beetje tegen jullie op en prijs mijzelf keer op keer gelukkig dat ik deel uit mag maken van jullie leven, want wat zijn jullie individueel en als een groep een ontzettend fijne mensen. Altijd in voor gekkigheid, serieuze gesprekken of discussies en onzin verhalen. Ik hoop dat we nog vaak op weekendjes weg kunnen gaan. Zo niet, dan reis ik met liefde stad en land af om jullie op te zoeken, van Lent tot 's Gravendeel, van Nijmegen tot Rotterdam, van Voorburg tot Zeist.

\newpage

Op woensdag 23 September 2009 ging ik kamerzoeken. In de avond kreeg ik een telefoontje: kom je wonen op Villa Drakensteijn? We gaan dit weekend op huisweekend, ga je dan ook gelijk mee? Kom je dan morgen ook vast een drankje mee drinken? Ja graag. Ja graag. Ja graag. Op dat weekend doken we een studio in en werd er een drakenlied geschreven dat begint als volgt:

*Daar was je dan, veranderde ons leven* <br/>\newline
*Een prominent studentenhuis,* <br/>\newline
*Voor elke draak een welkom thuis* <br/>\newline
*Een hechte band dat is ons streven.* 

Ik had geen idee hoe waar dit zou blijken. Stijn de Vrijer, mes que un amic. Jaren hebben we samen gewoond en hoe vaak we wel niet samen op vakantie zijn geweest weet ik ondertussen niet eens meer. Jelle, ondanks dat je in Barcelona woont hebben we elkaar vaak en op veel plekken kunnen zien tot mijn grote plezier. Bovendien is een eerdere draft van Hoofdstuk [5](#Burns) geschreven in jullie tuin terwijl ik op jullie huis mocht passen, waarvoor bedankt. Birgit, Jantine, Nora, Susan, Martijn, Joep, Jord, Mitchel, Else, Irene, en alle andere draken. Jullie hebben mijn leven veranderd en absoluut ten goede. 

Roel bedankt voor alle leuke, en verbazingwekkend genoeg soms ook sportieve, dagen. Want naast de gezellige biertjes, spelletjes en vakantie zijn we ook vaak samen wezen zwemmen, tennissen en fitnessen. Inken, Maarten, wat zijn jullie beide ontzettend fijne personen. Waar we ook rondhangen, wat we ook doen, het is altijd een waar genoegen. Voor alle onbenoemde Pythianen, bedankt voor alle mooie tijden die we al hebben gehad en die zeker ook nog gaan komen. 

Jeroen, Sjoerd en Wouter. Elke keer weer is een weekje in de bergen met jullie een absoluut hoogtepunt in mijn jaar. Ondertussen zien we elkaar ook meer buiten de wintersporten om en daar ben ik heel blij mee. 

Anne, je bent voor mij meer een vriendin geworden dan een collega, je enorme enthousiasme altijd is een genot.

Voor al mijn collega's, werken is veel leuker dan ik had verwacht en jullie zijn daar een groot gedeelte van de reden voor. Corine en Sanne, bedankt voor jaren van gezelligheid op de kamer. Ik ben bijna altijd met een lach naar werk gegaan en dat ik bij jullie op de kamer zat heeft daar zeker aan bijgedragen. Kimberley, Mariëlle, Fayette, Lientje, Oisín, Erik-Jan, Ayoub, Karlijn, Hidde, Jeroen, Sjoerd, Irene, Flip en alle andere leuke, fijne en gezellige collega's bedankt voor alle fijne jaren. Tot slot, Kevin, bedankt dat je alles altijd regelt en mee denkt naar de handigste oplossingen. Mede dankzij jou kan ik nog een paar maanden blijven op deze fijne afdeling. 




